# -*- coding: utf-8 -*-
"""Brishti-Final-Project-2-BigQuery bquxjob_1b346839_18a56b6481a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1elAi1pHSMbEhMTpRZEZim_zIjY7FfZ3d
"""

from google.colab import auth
import pandas as pd
# Will collect your credentials
auth.authenticate_user()

# Query Bigquery
project_id = 'lewagon-final-project-397408'
dataset = 'home_exchange'
table = 'dinis_finalized_exchanges'
query = f'SELECT * FROM {project_id}.{dataset}.{table}'
results = pd.read_gbq(query, project_id = project_id)
results.head()

results.describe()

# Query Bigquery
project_id = 'lewagon-final-project-397408'
dataset = 'home_exchange'
table = 'Brishti_finalized'
query = f'SELECT * FROM {project_id}.{dataset}.{table}'
df = pd.read_gbq(query, project_id = project_id)
df.head()



df.describe()

user_finalized = results.count()
user_finalized

user_finalized_churn = results.filled_churn.sum()
user_finalized_churn

user_not_finalized=df.count()
user_not_finalized

user_not_finalized_churn  = df.filled_churn.sum()
user_not_finalized_churn

user_finalized = 88835
user_finalized_churn= 36934

user_finalized_not_churn = user_finalized - user_finalized_churn
user_finalized_not_churn

user_not_finalized= 198177
user_not_finalized_churn= 43684

user_not_finalized_not_churn = user_not_finalized - user_not_finalized_churn
user_not_finalized_not_churn

user_finalized_churn=88835
user_finalized_not_churn=51901
user_not_finalized_churn=43684
user_not_finalized_not_churn=154493

import pandas as pd
import seaborn as sns
from scipy import stats

finalized = {'user_finalized_churn': user_finalized_churn,
           'user_finalized_not_churn': user_finalized_not_churn}
df = pd.DataFrame(list(finalized.items()), columns=['Finalized_Column_Name', 'Value'])

df

sns.barplot(df, x ='Finalized_Column_Name', y ='Value')

not_finalized = {'user_not_finalized_churn': user_not_finalized_churn,
           'user_not_finalized_not_churn': user_not_finalized_not_churn}
df = pd.DataFrame(list(not_finalized.items()), columns=['Not_Finalized_Column_Name', 'Value'])

sns.barplot(df, x ='Not_Finalized_Column_Name', y ='Value')

X = [[user_finalized_churn, user_finalized_not_churn],
     [user_not_finalized_churn, user_not_finalized_not_churn]]

df = pd.DataFrame(X)

df

df.keys

df = pd.DataFrame(X).T

df = df.rename(columns = {0:'Finalized', 1: 'Not_Finalized'})
df

# Assuming you have a DataFrame called df4_cleaned
# Calculate the average of “total_nights_sum” for each value of “renew”
average_nights_by_renew = df4_cleaned.groupby('renew')['total_nights_sum'].mean()
# Create the bar chart
plt.figure(figsize=(8, 6))
average_nights_by_renew.plot(kind='bar', color='skyblue')
plt.title('Average Total Nights Sum by Renew')
plt.xlabel('Renew (0 or 1)')
plt.ylabel('Average Total Nights Sum')
plt.xticks(rotation=0)
plt.show()

finalized_and_not_finalized = {'u_f_c': user_finalized_churn,
                                'u_f_n_c': user_finalized_not_churn,
                                 'u_n_f_c': user_not_finalized_churn,
                                 'u_n_f_n_c': user_not_finalized_not_churn}
df = pd.DataFrame(list(finalized_and_not_finalized.items()), columns=['finalized_and_not_finalized_Column_Name', 'Value'])

df.keys

X = [[user_finalized_churn, user_finalized_not_churn],
     [user_not_finalized_churn, user_not_finalized_not_churn]]

from scipy.stats import chi2_contingency

chi2, p_value, dof, expected = chi2_contingency(X)

print(f"chi2:{chi2}, p_value:{p_value},dof:{dof},expected:{expected}")
